# Generated by Django 5.2.6 on 2025-10-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='login',
            field=models.CharField(max_length=25, unique=True, verbose_name='Логин'),
        ),
    ]
